

spring:
  application:
    name: crawling
  config:
    import: "optional:file:.env[.properties]"
  data:
    mongodb:
      uri: mongodb://admin:1234@localhost:27017/crawling_db?authSource=admin
  ai:
    google:
      genai:
        project-id: ${GOOGLE_PROJECT_ID}
        api-key: ${GOOGLE_API_KEY}
        location: us-central1
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.7
            max-output-tokens: 20000

logging:
  level:
    org.springframework.ai: DEBUG
server:
  port: 9090